apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointments
  labels:
    app: appointments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointments
  template:
    metadata:
      labels:
        app: appointments
    spec:
      containers:
        - name: appointments
          image: 779846789022.dkr.ecr.ap-south-1.amazonaws.com/appointments:1.0.0
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ecr-secret
