apiVersion: v1
kind: Service
metadata:
  name: openmrs
  labels:
    app: openmrs
spec:
  type: LoadBalancer  # Only accessible inside the cluster (default)
  selector:
    app: openmrs    # Matches the pod label
  ports:
    - protocol: TCP
      port: 8080          # Port to expose on the service
      targetPort: 8080    # Port the container listens on