apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmrs-db
  labels:
    app: openmrs-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openmrs-db
  template:
    metadata:
      labels:
        app: openmrs-db
    spec:
      containers:
        - name: openmrs-db
          image: 779846789022.dkr.ecr.ap-south-1.amazonaws.com/openmrs-db:1.0.0-lite-mysql5.6
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: root-password
            - name: MYSQL_DATABASE
              value: openmrs
            - name: MYSQL_USER
              value: openmrs-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: user-password
      imagePullSecrets:
        - name: ecr-secret