apiVersion: apps/v1
kind: Deployment
metadata:
  name: crater-nginx
  labels:
    app: crater-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crater-nginx
  template:
    metadata:
      labels:
        app: crater-nginx
    spec:
      containers:
        - name: crater-nginx
          image: 779846789022.dkr.ecr.ap-south-1.amazonaws.com/crater-nginx:latest
          ports:
            - containerPort: 80
            - containerPort: 443
      imagePullSecrets:
        - name: ecr-registry-secret
