apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinic-config
  labels:
    app: clinic-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clinic-config
  template:
    metadata:
      labels:
        app: clinic-config
    spec:
      containers:
        - name: clinic-config
          image: 913524912266.dkr.ecr.ap-south-1.amazonaws.com/clinic-config:1.0.0
          ports:
            - containerPort: 80
          volumeMounts:
            - name: shared-config-volume
              mountPath: /shared/bahmni_config
          command: ["sh", "-c"]
          args:
            - |
              echo "Checking if config exists..."
              if [ -z "$(ls -A /shared/bahmni_config)" ]; then
                echo "No config found, copying default config..."
                mkdir -p /shared/bahmni_config/openmrs/apps/home
                cp -r /etc/bahmni_config/* /shared/bahmni_config/
                echo "Config copied successfully!"
              else
                echo "Config already exists. Skipping copy."
              fi
              ls -la /shared/bahmni_config/
              tail -f /dev/null

      volumes:
        - name: shared-config-volume
          persistentVolumeClaim:
            claimName: bahmni-config-pvc

      imagePullSecrets:
        - name: ecr-secret
