# apiVersion: v1
# kind: Service
# metadata:
#   name: implementer-interface
# spec:
#   type: ClusterIP
#   selector:
#     app: implementer-interface
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
