# apiVersion: v1
# kind: Service
# metadata:
#   name: reports-db
#   labels:
#     app: reports-db
# spec:
#   selector:
#     app: reports-db
#   ports:
#     - protocol: TCP
#       port: 3306
#       targetPort: 3306
#   type: ClusterIP
