apiVersion: apps/v1
kind: Deployment
metadata:
  name: bahmni-lab
  labels:
    app: bahmni-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bahmni-lab
  template:
    metadata:
      labels:
        app: bahmni-lab
    spec:
      containers:
        - name: bahmni-lab
          image: 913524912266.dkr.ecr.ap-south-1.amazonaws.com/bahmni-lab:1.0.0
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ecr-secret
